GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjk3NzExMDM0LCJleHAiOjE2OTc3MTEwNjR9.s6OqlsZgkc7DS3BmqAmBZ4EO3sE0jr-1YjD2xnJgepw

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwicGFzc3dvcmQiOiJhcmNoaXNoIiwiaWF0IjoxNjk3NzEwOTcyfQ.jWClpstEbicLNvwrhKPY75ZdRV5g4BfgRRRbQ5NW-2U"
}



###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwicGFzc3dvcmQiOiJhcmNoaXNoIiwiaWF0IjoxNjk3NzEwOTcyfQ.jWClpstEbicLNvwrhKPY75ZdRV5g4BfgRRRbQ5NW-2U"
}

###
POST http://localhost:4000/login 
Content-Type: application/json

{
    "username": "Jim",
    "password":"archish"
}

###
GET http://localhost:3000/check

###

