GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFyY2hpc2giLCJwYXNzd29yZCI6IjAyMTAiLCJpYXQiOjE2OTc5MTIzMzl9.8BWj3Xpv9pdrC9Ru_l5josaywKzXvZYEQsaarePTlcU

###
POST http://localhost:4000/login 
Content-Type: application/json

{
    "username": "Archish",
    "password": "0210"
}

###
GET http://localhost:3000/check

###

